"""
Django settings for online_store project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ct)(njt)x199pp*wgzh^w(6%xhnv$=(-!h@s103yv5=6=_34pe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'productos',
    'usuarios',
    'pedidos',
    'pagos',
    'carrito',

    'django.contrib.sites',  # django auth settings 
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'cloudinary',
    'cloudinary_storage'
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',#django auth setting
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'online_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'online_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

#imagenes
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

CLOUDINARY_STORAGE = {
  'CLOUD_NAME': 'dc8lc4pnl',
  'API_KEY': '759344413787729',
  'API_SECRET': 'VPXMU5o79qEb_70psXfTWt8MLSM',  
}



MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#Modo test
STRIPE_PUBLIC_KEY='pk_test_51RiTtaPJ2yFKupFRZZvT1LVsAEaravS1tA2SbPSJ3SMhZLlKCxCPiwKPzXn3ZbI5A7CBU7h9hk44EaE4ImUWZlfb00ao0KVUyB'
STRIPE_SECRET_KEY='sk_test_51RiTtaPJ2yFKupFRxvNKUNwvGhgvLJSl4bTlpPTAhIihb5ufqOIUY9sbxN2WO65HDKpCuAd383U7vDwKZSbH7g6V00EtwLRz4I'
STRIPE_WEBHOOK_SECRET='whsec_8cbff42ceea3b18d85931b52870ee3990a108fab21e7640872ab323e502b92b6'


AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # auth normal
    'allauth.account.auth_backends.AuthenticationBackend',  # para social
]

SITE_ID = 1

ACCOUNT_EMAIL_VERIFICATION = "none"






ACCOUNT_LOGIN_METHODS = {'username'}  # o {'username'}, o ambos {'username', 'email'}

ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

SOCIALACCOUNT_QUERY_EMAIL = True

LOGIN_REDIRECT_URL = '/'

SOCIALACCOUNT_AUTO_SIGNUP=True



ACCOUNT_FORMS = {
    'signup': 'usuarios.forms.CustomSignupForm',
    'login':'usuarios.forms.CustomLoginForm',
}