# Generated by Django 5.2.3 on 2025-07-07 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_alter_orderitem_quantity'),
        ('usuarios', '0002_remove_shippingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.shippingaddress'),
        ),
    ]
