# Generated by Django 5.2.4 on 2025-07-14 02:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_order_entregado_order_enviado'),
        ('productos', '0005_product_visible'),
        ('usuarios', '0002_remove_shippingaddress_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='entregado',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='enviado',
            new_name='sent',
        ),
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('sent', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('date_ordered', models.DateField(auto_now_add=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.shippingaddress')),
            ],
        ),
        migrations.CreateModel(
            name='GuestOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.guestorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product')),
            ],
        ),
    ]
