# Generated by Django 5.2.4 on 2025-07-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0006_rename_entregado_order_delivered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestorder',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
